
version: '2'

networks:
  custom:

services:

  ca.org1.example.com:
    image: hyperledger/fabric-ca:amd64-1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/msp/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/msp/{{ ca_org1_keyfile }}
      # CA SERVER BCCSP OPTIONS
      - FABRIC_CA_SERVER_BCCSP_DEFAULT=PKCS11
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - FABRIC_CA_SERVER_BCCSP_PKCS11_PIN=98765432
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LABEL=ForFabric
      - FABRIC_CA_SERVER_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric-ca-server/msp/keystore
      - FABRIC_CA_SERVER_BCCSP_PKCS11_HASH=SHA2
      - FABRIC_CA_SERVER_BCCSP_PKCS11_SECURITY=256
    ports:
      - "7054:7054"
    command: sh -c 'bash /tmp/install/setup.sh && fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network_resources/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server/msp
      - ../network_resources/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml:ro
      - ./setup.sh:/tmp/install/setup.sh:ro
    container_name: ca_peerOrg1
    networks:
      - custom

  ca.org2.example.com:
    image: hyperledger/fabric-ca:amd64-1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/msp/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/msp/{{ ca_org2_keyfile }}
      # CA SERVER BCCSP OPTIONS
      - FABRIC_CA_SERVER_BCCSP_DEFAULT=PKCS11
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - FABRIC_CA_SERVER_BCCSP_PKCS11_PIN=98765432
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LABEL=ForFabric
      - FABRIC_CA_SERVER_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric-ca-server/msp/keystore
      - FABRIC_CA_SERVER_BCCSP_PKCS11_HASH=SHA2
      - FABRIC_CA_SERVER_BCCSP_PKCS11_SECURITY=256
    ports:
      - "8054:7054"
    command: sh -c 'bash /tmp/install/setup.sh && fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network_resources/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server/msp
      - ../network_resources/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml:ro
      - ./setup.sh:/tmp/install/setup.sh:ro
    container_name: ca_peerOrg2
    networks:
      - custom

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:amd64-1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      # ORDERER BCCSP OPTIONS
      - ORDERER_GENERAL_BCCSP_DEFAULT=PKCS11
      - ORDERER_GENERAL_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - ORDERER_GENERAL_BCCSP_PKCS11_PIN=98765432
      - ORDERER_GENERAL_BCCSP_PKCS11_LABEL=ForFabric
      - ORDERER_GENERAL_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/msp/orderer/msp/keystore
      - ORDERER_GENERAL_BCCSP_PKCS11_HASH=SHA2
      - ORDERER_GENERAL_BCCSP_PKCS11_SECURITY=256
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: sh -c 'bash /tmp/install/setup.sh && orderer'
    networks:
      - custom
    ports:
      - 7050:7050
    volumes:
        - ../network_resources/config/:/etc/hyperledger/configtx
        - ../network_resources/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/hyperledger/msp/peerOrg2
        - ../network_resources/orderer.yaml:/etc/hyperledger/msp/orderer/orderer.yaml:ro
        - ./setup.sh:/tmp/install/setup.sh:ro

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:amd64-1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
      # PEER BCCSP OPTIONS
      - CORE_PEER_BCCSP_DEFAULT=PKCS11
      - CORE_PEER_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - CORE_PEER_BCCSP_PKCS11_PIN=98765432
      - CORE_PEER_BCCSP_PKCS11_LABEL=ForFabric
      - CORE_PEER_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_PEER_BCCSP_PKCS11_HASH=SHA2
      - CORE_PEER_BCCSP_PKCS11_SECURITY=256
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c 'bash /tmp/install/setup.sh && peer node start'
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - custom
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
        - ./setup.sh:/tmp/install/setup.sh:ro
    depends_on:
      - orderer.example.com

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:amd64-1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
      # PEER BCCSP OPTIONS
      - CORE_PEER_BCCSP_DEFAULT=PKCS11
      - CORE_PEER_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - CORE_PEER_BCCSP_PKCS11_PIN=98765432
      - CORE_PEER_BCCSP_PKCS11_LABEL=ForFabric
      - CORE_PEER_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_PEER_BCCSP_PKCS11_HASH=SHA2
      - CORE_PEER_BCCSP_PKCS11_SECURITY=256
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c 'bash /tmp/install/setup.sh && peer node start'
    networks:
      - custom
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
        - ./setup.sh:/tmp/install/setup.sh:ro
    depends_on:
      - orderer.example.com

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:amd64-1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
      # PEER BCCSP OPTIONS
      - CORE_PEER_BCCSP_DEFAULT=PKCS11
      - CORE_PEER_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - CORE_PEER_BCCSP_PKCS11_PIN=98765432
      - CORE_PEER_BCCSP_PKCS11_LABEL=ForFabric
      - CORE_PEER_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_PEER_BCCSP_PKCS11_HASH=SHA2
      - CORE_PEER_BCCSP_PKCS11_SECURITY=256
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c 'bash /tmp/install/setup.sh && peer node start'
    networks:
      - custom
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
        - ./setup.sh:/tmp/install/setup.sh:ro
    depends_on:
      - orderer.example.com

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer:amd64-1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
      # PEER BCCSP OPTIONS
      - CORE_PEER_BCCSP_DEFAULT=PKCS11
      - CORE_PEER_BCCSP_PKCS11_LIBRARY=/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
      - CORE_PEER_BCCSP_PKCS11_PIN=98765432
      - CORE_PEER_BCCSP_PKCS11_LABEL=ForFabric
      - CORE_PEER_BCCSP_PKCS11_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/msp/keystore
      - CORE_PEER_BCCSP_PKCS11_HASH=SHA2
      - CORE_PEER_BCCSP_PKCS11_SECURITY=256
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: sh -c 'bash /tmp/install/setup.sh && peer node start'
    networks:
      - custom
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network_resources/crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
        - ../network_resources/config:/etc/hyperledger/configtx
        - ./setup.sh:/tmp/install/setup.sh:ro
    depends_on:
      - orderer.example.com
